### ISSUE TITLE
5.2がymlに記述されていない問題について

### ISSUE THREAD

**Issue by ichiki1023** [ichiki1023/rws-php-sdk#1]
ドキュメントの動作要件にはPHP5.2.3以上と記述されているにもかかわらず、
ymlにはphp5.3~5.6までしか記述されていない。

なぜでしょうか。また、8.0などPHPで定義されていないバージョンを指定したらどうなるのか。

https://github.com/rakuten-ws/rws-php-sdk/blob/master/.travis.yml

``` yml
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
```
